CREATE TABLE IF NOT EXISTS snippets (
                                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                                        title TEXT,
                                        language TEXT,
                                        code TEXT,
                                        tags TEXT
);

INSERT INTO snippets (title, language, code, tags) VALUES

                                                       ('Reverse String', 'Java', 'new StringBuilder(str).reverse().toString();', 'string,java'),
                                                       ('Two Sum', 'Java', 'for(int i=0;i<n;i++){for(int j=i+1;j<n;j++){if(a[i]+a[j]==t)return;}}', 'array'),
                                                       ('Factorial', 'Java', 'int f=1;for(int i=1;i<=n;i++)f*=i;', 'math'),
                                                       ('Binary Search', 'Java', 'while(l<=r){int m=(l+r)/2;}', 'search'),
                                                       ('Palindrome Check', 'Java', 'if(str.equals(new StringBuilder(str).reverse().toString()))', 'string'),
                                                       ('Sort Array', 'Java', 'Arrays.sort(arr);', 'array'),
                                                       ('Fibonacci', 'Java', 'int a=0,b=1;', 'math'),
                                                       ('Find Max', 'Java', 'int max = Arrays.stream(arr).max().getAsInt();', 'array'),
                                                       ('Swap Numbers', 'Java', 'a=a+b;b=a-b;a=a-b;', 'math'),
                                                       ('Count Digits', 'Java', 'while(n>0){count++;n/=10;}', 'math'),

                                                       ('Hello World', 'Python', 'print("Hello World")', 'basic'),
                                                       ('Reverse List', 'Python', 'lst[::-1]', 'list'),
                                                       ('Factorial', 'Python', 'import math; math.factorial(n)', 'math'),
                                                       ('Sort List', 'Python', 'lst.sort()', 'list'),
                                                       ('Lambda Example', 'Python', 'lambda x: x*2', 'lambda'),
                                                       ('List Comprehension', 'Python', '[x*x for x in range(10)]', 'list'),
                                                       ('Dictionary Access', 'Python', 'd.get("key")', 'dict'),
                                                       ('File Read', 'Python', 'open("file.txt").read()', 'file'),
                                                       ('Find Max', 'Python', 'max(lst)', 'list'),
                                                       ('String Split', 'Python', 'str.split()', 'string'),

                                                       ('Select All', 'SQL', 'SELECT * FROM table;', 'sql'),
                                                       ('Where Clause', 'SQL', 'SELECT * FROM table WHERE id=1;', 'sql'),
                                                       ('Insert Row', 'SQL', 'INSERT INTO table VALUES(...);', 'sql'),
                                                       ('Update Row', 'SQL', 'UPDATE table SET col=val;', 'sql'),
                                                       ('Delete Row', 'SQL', 'DELETE FROM table WHERE id=1;', 'sql'),
                                                       ('Join Tables', 'SQL', 'SELECT * FROM A JOIN B ON A.id=B.id;', 'sql'),
                                                       ('Group By', 'SQL', 'SELECT col,COUNT(*) FROM table GROUP BY col;', 'sql'),
                                                       ('Order By', 'SQL', 'SELECT * FROM table ORDER BY col DESC;', 'sql'),
                                                       ('Limit', 'SQL', 'SELECT * FROM table LIMIT 10;', 'sql'),
                                                       ('Count Rows', 'SQL', 'SELECT COUNT(*) FROM table;', 'sql'),

                                                       ('DFS', 'Java', 'dfs(node.left); dfs(node.right);', 'tree'),
                                                       ('BFS', 'Java', 'Queue<Integer> q = new LinkedList<>();', 'tree'),
                                                       ('Stack Push', 'Java', 'stack.push(x);', 'stack'),
                                                       ('Queue Add', 'Java', 'queue.add(x);', 'queue'),
                                                       ('HashMap Put', 'Java', 'map.put(key,val);', 'map'),
                                                       ('Set Add', 'Java', 'set.add(x);', 'set'),
                                                       ('Thread Create', 'Java', 'new Thread(() -> {}).start();', 'thread'),
                                                       ('Exception Handling', 'Java', 'try{} catch(Exception e){}', 'exception'),
                                                       ('File Write', 'Java', 'Files.write(path,data);', 'file'),
                                                       ('String Length', 'Java', 'str.length();', 'string'),

                                                       ('Merge Sort', 'Java', 'mergeSort(arr,0,n-1);', 'sorting'),
                                                       ('Quick Sort', 'Java', 'quickSort(arr,low,high);', 'sorting'),
                                                       ('DP Fibonacci', 'Java', 'dp[i]=dp[i-1]+dp[i-2];', 'dp'),
                                                       ('Kadane Algo', 'Java', 'max=Math.max(curr,max);', 'array'),
                                                       ('Anagram Check', 'Java', 'Arrays.sort(a);Arrays.sort(b);', 'string'),
                                                       ('Matrix Transpose', 'Java', 'res[j][i]=a[i][j];', 'matrix'),
                                                       ('Prime Check', 'Java', 'for(int i=2;i*i<=n;i++)', 'math'),
                                                       ('GCD', 'Java', 'return gcd(b,a%b);', 'math'),
                                                       ('LCM', 'Java', 'lcm=(a*b)/gcd(a,b);', 'math'),
                                                       ('Power', 'Java', 'Math.pow(a,b);', 'math');